portfolio-setup
MILINDI7/portfolio-template-1 pull request #2
Opened 2022-09-21 15:37 UTC by MILINDI7

## What?
Setting up the portfolio skeleton and adding the first section that includes the navigation and first about section.

## Why?
As specified in the requirements of the project, we should add the first section of the portfolio.

## How?
After creating the HTML skeleton and styling the first section in VS CODE using the remote branch, it's time to require their merge.

2022-09-21 20:35 UTC, tugsem requested changes
Hi @MILINDI7, 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!
![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights ⭐ 
:heavy_check_mark: You used correct Github Flow,
:heavy_check_mark: Your PR and commits are descriptive,
:heavy_check_mark: All linters are passing.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 20:35 UTC, tugsem commented on index.html
> +      </nav>
- [ ] Kindly use `header` tag here for wrapping both the logo and the hamburger button. It is semantically more correct to do.

2022-09-21 20:35 UTC, tugsem commented on index.html
> +        </div>
- [ ] Kindly use nav tag here for wrapping the button on the right side of header. You should use a link tag or button tag here. This is for three reasons: convention, semantics, and user experience.

2022-09-21 20:35 UTC, tugsem commented on index.html
> +  </main>
- [ ] This part of the page should be wrapped inside the section tag. It represents a generic standalone section of the document, so use it. Also, kindly implement the right background image to your background like the figma design here: 
![image](https://user-images.githubusercontent.com/91486791/191604829-61bacdc0-1a0a-4f14-bd3a-2121a81a815d.png)

2022-09-21 20:35 UTC, tugsem commented on index.html
> +          <a href="#">LET’S CONNECT</a>
- [ ] Here, 'let's connect' is just a title. please use header tag or p tag. The purpose here to make navigation elements clickable, not subtitles.

2022-09-21 20:35 UTC, tugsem commented on index.html
> +        </div>
- [ ] The list of icons should have a ul tag to group them, and li per icon; each icon has a link (a tag).

Apart from being semantically correct, the a tag will let you connect your social networks with the icons, using href. So please use them.

2022-09-22 15:24 UTC, MILINDI7 commented on index.html
> +      </nav>
Thank you, but I think as long as the div has a class that specifies it as a header it is not a big issue.

2022-09-22 15:29 UTC, MILINDI7 commented on index.html
> +        </div>
Thank you, but as long as it is a div contained in a nav tag such that both nav contents are in, I guess it is not an issue. I will change about making it a link.

2022-09-22 21:59 UTC, ichala approved these changes
Hi @MILINDI7 ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implement✔️

 Good job implementing the required changes :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


*************************************
# Optional Suggestions 

- [ ] **_check comments below_**


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 21:59 UTC, ichala commented on index.css
> +}
- [OPTIONAL] for best CSS practices  If you want to create a CSS rule for multiple elements, use a class attribute instead. For example, instead of using `font-family: 'Poppins', sans-serif;` 3 times you can create a class and add it to all elements that need to be popping family.



 ```CSS
 .poppins {font-family: font-family: 'Poppins', sans-serif;}
```

2022-09-22 22:08 UTC, merged