mobile-first
MILINDI7/portfolio-template-1 pull request #3
Opened 2022-09-24 16:41 UTC by MILINDI7

## What?
Add the four other sections so-called cards and the last one about us.

## Why?
Due to the project request.

## How?
By the use of vscode and flex-box and css-grid we created a good semantic and styling of a mobile first portfoilia.

2022-09-24 18:21 UTC, mgmediaweb requested changes
Hi @MILINDI7, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost2](https://user-images.githubusercontent.com/41912912/192112170-89641cc4-2453-47e1-b2af-ab541b121536.gif)

## Highlights 💯 
- Professional-looking readme file. ✔️ 
- Clear and descriptive Pull Request. ✔️ 
- Clean and tidy code. ✔️ 
- Good job following the design. ✔️ 
- Good job following the advice of the previous reviewer ✔️ 

## Required Changes ♻️

Kindly, I recommend you remove these margins, to make your site look more professional
![image](https://user-images.githubusercontent.com/41912912/192112840-fb88c500-54f7-4963-9a40-f1f5baccdf0b.png)

Kindly, I recommend changing the text of this button to look like the original design of Figma
![image](https://user-images.githubusercontent.com/41912912/192112993-abf17d4f-4009-4231-b31f-dce2123389aa.png)

- Kindly, your site shows a horizontal scroll, I suggest you check what element is causing it and adjust it

_Check the comments under the review._

## Optional suggestions

[OPTIONAL] Kindly, I suggest you use "ARTICLE" semantic tags for each project

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 18:21 UTC, mgmediaweb commented on index.html
> +            </div>
I kindly suggest you use UL/LI listings to display this information, the dot you can use a fontawesome icon

2022-09-24 18:21 UTC, mgmediaweb commented on index.html
> +            </div>
I kindly suggest you use UL/LI listings to display this information, the dot you can use a fontawesome icon

2022-09-24 18:21 UTC, mgmediaweb commented on index.html
> +            </div>
I kindly suggest you use UL/LI listings to display this information, the dot you can use a fontawesome icon

2022-09-24 18:21 UTC, mgmediaweb commented on index.html
> +            </div>
I kindly suggest you use UL/LI listings to display this information, the dot you can use a fontawesome icon

2022-09-24 18:21 UTC, mgmediaweb commented on index.html
> +    </div>
Kindly, I suggest you use all those shapes in a single image that is set as background. (line 64 - 90)

2022-09-24 18:21 UTC, mgmediaweb commented on index.css
> +  height: 600px;
Kindly, I advise you not to use fixed measures. it is preferable to use percentages so that your page adapts to any size of mobile device

2022-09-24 19:19 UTC, mucyoalexaxel commented on index.html
> +          </div>
Thank you for your suggestion but the folliwng information are not relavant.

2022-09-24 23:22 UTC, jerryowusu requested changes
Hi @MILINDI7 :wave: 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. I know it can be frustrating sometimes, especially when you are working under stress, but trust me, these are the kind of guidelines that help make you a better developer. 


![so close](https://user-images.githubusercontent.com/65233860/192121373-71293e66-2aed-4de9-b0b1-aae268aacb65.gif)

 ## Highlights
Clear and descriptive Pull Request. :heavy_check_mark:
Clean and tidy code. :heavy_check_mark:

 ## Required Changes ♻️

- [ ] As show in the image below (_check the 3rd and 4th bullet points_), it is part of the project requirements to use ul and li for listing all item sin the `Work` and `About Myself` section. As the previous reviewer pointed out, kindly check and make sure that all such listings in your code conforms to this rule. Some of these changes can be made on lines `103 - 14`, `153 - 164`, `201 - 211`, `249 - 260`, `325 - 352` etc

![Screenshot from 2022-09-24 12-11-24](https://user-images.githubusercontent.com/65233860/192121617-d93d2935-09ed-4476-8d5b-877f3ea2ee28.png)

- [ ] The previous reviewer talked about removing `margins` from around your design. Kindly work on that since it is not making your design conform to that of the original figma design. 

![Screenshot from 2022-09-24 23-11-19](https://user-images.githubusercontent.com/65233860/192121813-b0633b0d-fd28-4002-a4df-7f6a5b615a89.png)


![Screenshot from 2022-09-24 23-11-47](https://user-images.githubusercontent.com/65233860/192121810-889df2a9-7866-4ef0-a0ef-50cef26d3bd3.png)


_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] The `languages`, `Frameworks`, and  `Skills` lists each has an arrow to the right side (_as shown in the figma design image below_) which you missed. Kindly check and add them since it will make your project more meaningful and conform to the figma design.

Figma design

![Screenshot from 2022-09-24 23-14-49](https://user-images.githubusercontent.com/65233860/192121973-8b5292aa-ec16-4d5d-b065-e2e8a4bd9b9d.png)

Your design
![Screenshot from 2022-09-24 23-13-23](https://user-images.githubusercontent.com/65233860/192121976-c748dab9-819b-448c-a457-826db0670355.png)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 23:43 UTC, karlavdelgadof requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @MILINDI7  :wave: :technologist: !

Your project is looking fantastic so far :star_struck: ! 

However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses: 

![](https://media.giphy.com/media/Jir7AUookJHIVb5aYM/giphy.gif)

## :sparkles: Highlights :sparkles:

- Great work using the right GitHub Flow :100: 
- Awesome file organization :card_file_box: 
- Commits are descriptive and meaningful :+1: 
- Project Documentation (PR, README) is professional :necktie: 

Congrats on your work so far! :clap:  

## Required Changes ♻️
There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@karlavdelgadof**  in your question so I can receive the notification.
  
  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
  
  ------
  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 23:43 UTC, karlavdelgadof commented on index.css
- [ ] As mentioned by the previous reviewer, I suggest setting your body element `margin/padding` to 0, in this way your design will match the Figma Template :heavy_check_mark: 

**Your Project:**
![image](https://user-images.githubusercontent.com/92395484/192121974-4624aa91-6481-4c1a-b695-e884e9694906.png)

**Figma Template:**
![image](https://user-images.githubusercontent.com/92395484/192122212-bbee6f7c-bdd0-483f-aa7c-4228b5f8471e.png)

As you can see, there is no space in this section :eyes:

2022-09-24 23:43 UTC, karlavdelgadof commented on index.html
> +    <section class="first-card">
- [ ] For the project cards, I will suggest using a bigger container like `<section>` tag, and inside each card will be a `<div>` or an `<article>`. In this way, you can accomplish a cleaner structure and also apply the CSS grid to align this section as mentioned in the [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md) :heavy_check_mark: :sparkles:

2022-10-01 17:21 UTC, Nemwel-Boniface approved these changes
## Hello @MILINDI7        :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making all the requested changes good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-01 17:21 UTC, Nemwel-Boniface commented on index.html
>        </div>
- [ ] [OPTIONAL] Kindly reduce the margin/ padding (spacing) top and bottom between each individual project. This way your project will really closely match the provided Figma design.

**This is how I can see the sections:**

![image](https://user-images.githubusercontent.com/86318284/193420723-86a11f56-ad57-4569-bb39-6a23dfb60271.png)

2022-10-01 17:42 UTC, merged