Desktop-version-with-media-queries
MILINDI7/portfolio-template-1 pull request #5
Opened 2022-10-07 15:10 UTC by MILINDI7

## What?
To add the content of the desktop version and style them using the media queries.

## Why?
Due to the project requirements, we are supposed to add and change our portfolio into a responsive one using media queries.

## How?
By the use of VS Code, HTML semantic tags and CSS with the help of media queries, I managed to change my portfolio into a responsive one.

2022-10-07 16:07 UTC, levy002 requested changes
## Hello @MILINDI7   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 20:24 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @jossi30, I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
Kinndly make sure 

https://github.com/MILINDI7/portfolio-template-1/pull/5#discussion_r990250495

2022-10-07 20:24 UTC, MaganaAsiati commented on index.html
> +            I’m Mariane <br> Glad to see you!
- [ ] kindly make sure the mobile many are not visible in the desktop version as it shows in the Figma design so that your design will stick to the Figma design as was required. check below your design compared to the Figma design :grinning: :grinning: :grinning: 

## Figma design 

![image](https://user-images.githubusercontent.com/95297251/194646846-bfef6e30-aa44-4d34-aac1-8091b44b7f5c.png)

## Your design 

![image](https://user-images.githubusercontent.com/95297251/194646697-6bd0a542-f570-40cc-8bd5-0f01cd5846cf.png)

2022-10-08 07:30 UTC, Kamba56 approved these changes
Hi @MILINDI7, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [x] All linters passed
- [ ] Great use of GIthub flow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-08 07:30 UTC, Kamba56 commented on index.css
> +  .first-header {
- [Optional] Your whole portfolio overflows horizontally, one has to scroll to the right to see the nav and other parts of the page. Kindly fix this, please.
![5](https://user-images.githubusercontent.com/94551484/194695721-fce78c37-f1d1-44db-a143-820e7dd96ee9.png)

2022-10-08 07:33 UTC, merged